{
 "title": "GRAPEVINE HPC Job and Partition metrics (sent by HPC SLURM exporter)",
 "description": "Dashboard for the prometheus hpc exporters [SLURM]",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "deployment_label",
    "label": "Deployment Label",
    "query": "label_values(slurm_partition_availability, deployment_label)"
   },
   {
    "name": "job_id",
    "label": "Job ID",
    "query": "label_values(slurm_job_state{deployment_label=~\"$deployment_label\"}, job_id)"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "label_values(slurm_partition_availability{deployment_label=~\"$deployment_label\"},partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global info (associated deployment)，Deployment：$deployment_label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Job information【Deployment：$deployment_label】",
   "type": "table-old",
   "description": "Job information of the jobs selected for monitoring.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "slurm_job_cpu_n{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "ncpus"
    },
    {
     "expr": "slurm_job_state{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "state"
    },
    {
     "expr": "slurm_job_walltime_used{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "walltime used"
    },
    {
     "expr": "slurm_job_queued{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "time queued"
    },
    {
     "expr": "slurm_job_memory_virtual_max{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "vmem max"
    },
    {
     "expr": "slurm_job_memory_physical_max{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "pmem max"
    },
    {
     "expr": "slurm_job_exit_code{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "exit status"
    },
    {
     "expr": "slurm_job_exit_signal{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "exit signal"
    }
   ]
  },
  {
   "title": "Partition information【Deployment：$deployment_label】",
   "type": "table-old",
   "description": "Partition information.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "slurm_partition_availability{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "availability"
    },
    {
     "expr": "slurm_partition_cores_total{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "total"
    },
    {
     "expr": "slurm_partition_cores_allocated{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "allocated"
    },
    {
     "expr": "slurm_partition_cores_idle{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "idle"
    },
    {
     "expr": "slurm_partition_cores_total{deployment_label=~\"$deployment_label\"}-slurm_partition_cores_allocated{deployment_label=~\"$deployment_label\"}-slurm_partition_cores_idle{deployment_label=~\"$deployment_label\"}",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Job info (associated deployment)，Job ID：$job_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Job State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_job_state{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    }
   ]
  },
  {
   "title": "Maximum virtual memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "slurm_job_memory_virtual_max{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Maximum physical memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "slurm_job_memory_physical_max{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Job walltime used",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slurm_job_walltime_used{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    }
   ]
  },
  {
   "title": "Partition info (associated deployment)，partition：$partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Partition availability",
   "type": "graph",
   "description": "Availability of the selected partition",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_availability{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Partition nodes state: $partition",
   "type": "graph",
   "description": "Number of nodes in each state",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_cores_allocated{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "slurm_partition_cores_idle{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "slurm_partition_cores_total{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}-slurm_partition_cores_allocated{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}-slurm_partition_cores_idle{deployment_label=~\"$deployment_label\",partition=~\"$partition\"}",
     "legendFormat": "Others"
    }
   ]
  }
 ]
}